import Head from "next/head";

const SEO = ({ pageTitle }) => (
  <>
    <Head>
      <title>{pageTitle && `${pageTitle} - Vserve Australia `}</title>
      <meta httpEquiv="x-ua-compatible" content="ie=edge" />
      <meta
        name="description"
        content="Vserve Australia is a service which connects the mental health condition, the physically impaired and those with special needs to services that provide them with assistance. We understand that individuals and families require lots of support and care to be able to enjoy themselves and live the life they desire. Vserve Australia is an independent service that has been successfully established and running within all areas of the Sydney region."
      />
      {/* <meta name="robots" content="noindex, follow" /> */}
      <meta
        property="og:url"
        content="https://vserve-australia-6tyv.vercel.app"
      />
      <meta property="og:type" content="website" />
      <meta property="og:title" content="Home Two - Vserve Australia " />
      <meta property="og:description" content="Generated by create next app" />
      <meta property="og:image" content="" />

      {/* <!-- Twitter Meta Tags --> */}
      <meta name="twitter:card" content="summary_large_image" />
      <meta name="twitter:title" content="Home Two - Vserve Australia " />
      <meta name="twitter:description" content="Generated by create next app" />
      <meta name="twitter:image" content=""></meta>
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no"
      />
      <link rel="icon" href="/favicon.png" />
    </Head>
  </>
);

export default SEO;
